import {
    BadRequestException,
    Injectable,
    InternalServerErrorException,
    NotFoundException,
} from '@nestjs/common';

import {
    InjectModel,
} from '@nestjs/mongoose';

import {
    Model,
} from 'mongoose';

import {
    GoogleGenAI,
} from '@google/genai';

import {
    Profile,
    ProfileDocument,
} from '../profiles/schemas/profile.schema';

import {
    JobAnalysis,
    JobAnalysisDocument,
} from './schemas/job-analysis.schema';

import {
    MarketDemand,
    MarketDemandDocument,
} from '../market-demand/schemas/market-demand.schema';


@Injectable()
export class JobAnalysisService {

    private readonly gemini: GoogleGenAI;


    constructor(

        @InjectModel(Profile.name)
        private readonly profileModel:
            Model<ProfileDocument>,


        @InjectModel(JobAnalysis.name)
        private readonly jobAnalysisModel:
            Model<JobAnalysisDocument>,


        @InjectModel(MarketDemand.name)
        private readonly marketDemandModel:
            Model<MarketDemandDocument>,

    ) {

        const apiKey =
            process.env.GEMINI_API_KEY;


        if (!apiKey) {

            throw new Error(
                'GEMINI_API_KEY is missing in the .env file.',
            );

        }


        this.gemini =
            new GoogleGenAI({
                apiKey,
            });

    }


    async analyzeJob(userId: string) {

        // ==========================================
        // STEP 1: GET USER PROFILE
        // ==========================================

        const profile =
            await this.profileModel.findOne({
                userId,
            });


        if (!profile) {

            throw new NotFoundException(
                'Profile not found. Please create your profile first.',
            );

        }


        // ==========================================
        // STEP 2: CHECK JOB DESCRIPTION
        // ==========================================

        if (
            !profile.jobDescription ||
            profile.jobDescription.trim() === ''
        ) {

            throw new BadRequestException(
                'Please add a Job Description to your profile first.',
            );

        }


        // ==========================================
        // STEP 3: COMBINE USER SKILLS
        // ==========================================

        const userSkills = [

            ...new Set([

                ...(profile.skills || []),

                ...(profile.programmingLanguages || []),

            ]),

        ];


        // ==========================================
        // STEP 4: CREATE GEMINI PROMPT
        // ==========================================

        const prompt = `
You are an AI-powered Career Navigator.

Your task is to analyze a user's profile against
a target Job Description.

IMPORTANT:

The overall match percentage and learning roadmap
will NOT be generated by you.

Those values will be taken from the application's
Market Demand Analysis so that Career Explorer,
Market Demand Analysis, and Job Description Analysis
remain consistent.

Your job is only to:

1. Identify the most appropriate career/job role
   represented by the Job Description.

2. Identify skills the user already has that match
   the Job Description.

3. Identify missing skills.

4. Identify user strengths relevant to the job.

5. Provide explainable AI explanations.

6. Assign priorities to missing skills.

=================================
USER PROFILE
=================================

Skills:
${JSON.stringify(userSkills)}

Interests:
${JSON.stringify(profile.interests || [])}

Education:
${profile.education || 'Not provided'}

Bio:
${profile.bio || 'Not provided'}

GitHub Repositories:
${JSON.stringify(
            profile.githubRepositories || [],
        )}

Programming Languages:
${JSON.stringify(
            profile.programmingLanguages || [],
        )}

=================================
TARGET JOB DESCRIPTION
=================================

${profile.jobDescription}

=================================
CAREER IDENTIFICATION
=================================

Identify the main career/job role represented
by this Job Description.

Examples:

"Frontend Developer"
"Backend Developer"
"Full Stack Developer"
"Data Analyst"
"Cybersecurity Analyst"
"DevOps Engineer"

Use a concise standard career name.

Do NOT create an overly specific title based only
on a company-specific title.

For example:

"React Developer Intern"
should normally map to:

"Frontend Developer"

if the responsibilities are primarily frontend development.

=================================
SKILL ANALYSIS
=================================

Identify:

- Skills already possessed by the user that match
  the Job Description.
- Missing skills required by the Job Description.
- User strengths relevant to this role.

Do not invent:

- Skills
- Experience
- Projects
- Qualifications

Only use information available in:

- User Profile
- User Skills
- Programming Languages
- GitHub Information
- Job Description

=================================
PRIORITY LEVELS
=================================

You must ONLY use:

CRITICAL
HIGH
MEDIUM
SUPPORTING

CRITICAL:
Fundamental skill required for the role.

HIGH:
Very important for job readiness.

MEDIUM:
Useful and commonly expected.

SUPPORTING:
Helpful but secondary.

=================================
IMPORTANT PRIORITY RULE
=================================

Core technologies should have higher
priority than supporting tools.

For example:

JavaScript → CRITICAL

React → CRITICAL or HIGH

TypeScript → HIGH

Git/GitHub → SUPPORTING

unless Git/GitHub is explicitly a major
requirement in the Job Description.

=================================
EXPLAINABLE AI
=================================

For every missing skill explain:

- Why the skill is required.
- Why it received its priority.
- How learning it improves job readiness.

=================================
IMPORTANT
=================================

DO NOT generate:

- matchScore
- roadmap
- generalRoadmap
- estimated learning duration
- learning schedule

The application will obtain the match score
and roadmap from Market Demand Analysis.

=================================
RETURN ONLY VALID JSON
=================================

Return exactly this structure:

{
    "career": "Frontend Developer",

    "matchedSkills": [],

    "strengths": [],

    "explanations": [
        {
            "skill": "",
            "explanation": ""
        }
    ],

    "missingSkills": [
        {
            "skill": "",
            "priority": "CRITICAL",
            "priorityScore": 100,
            "reason": ""
        }
    ]
}
`;


        try {

            // ==========================================
            // STEP 5: SEND DATA TO GEMINI
            // WITH MODEL FALLBACK
            // ==========================================

            let response: any = null;

            // If GEMINI_MODEL exists in .env, try it first.
            // Otherwise use the default fallback order.

            const configuredModel =
                process.env.GEMINI_MODEL?.trim();

            const models: string[] = [
                ...(configuredModel
                    ? [configuredModel]
                    : []),

                'gemini-3.8-flash',
                'gemini-3.7-flash',
                'gemini-3.5-flash-lite',
            ];


            const maxRetriesPerModel = 2;

            let lastError: any = null;


            // ==========================================
            // TRY EACH MODEL
            // ==========================================

            for (const model of models) {

                console.log(
                    `Trying Gemini model for Job Analysis: ${model}`,
                );


                for (
                    let attempt = 1;
                    attempt <= maxRetriesPerModel;
                    attempt++
                ) {

                    try {

                        response =
                            await this.gemini.models.generateContent({

                                model,

                                contents: prompt,

                                config: {
                                    responseMimeType:
                                        'application/json',
                                },

                            });


                        console.log(
                            `Job Analysis Gemini succeeded using model: ${model}`,
                        );


                        break;

                    } catch (error: any) {

                        lastError = error;


                        const status =
                            error?.status ||
                            error?.error?.code;


                        console.error(
                            `Job Analysis Gemini ${model} attempt ${attempt} failed:`,
                            error?.message,
                        );


                        // ----------------------------------
                        // FALLBACK / RETRY CONDITIONS
                        // ----------------------------------
                        //
                        // 404 = model unavailable/not found
                        // 429 = rate limit
                        // 503 = service unavailable
                        //
                        // These should cause us to retry
                        // or move to the next model.
                        // ----------------------------------

                        if (
                            status !== 404 &&
                            status !== 429 &&
                            status !== 503
                        ) {

                            throw error;

                        }


                        if (
                            attempt < maxRetriesPerModel
                        ) {

                            const delay =
                                attempt * 2000;


                            console.log(
                                `Retrying ${model} in ${
                                    delay / 1000
                                } seconds...`,
                            );


                            await new Promise(
                                (resolve) =>
                                    setTimeout(
                                        resolve,
                                        delay,
                                    ),
                            );

                        }

                    }

                }


                // ----------------------------------
                // Model succeeded
                // ----------------------------------

                if (response) {

                    break;

                }


                console.log(
                    `${model} unavailable. Trying next Gemini model...`,
                );

            }


            // ==========================================
            // ALL MODELS FAILED
            // ==========================================

            if (!response) {

                throw lastError ||
                    new Error(
                        'All Gemini models failed.',
                    );

            }


            // ==========================================
            // STEP 6: CONVERT GEMINI JSON
            // ==========================================

            const content =
                response.text;


            if (!content) {

                throw new Error(
                    'Gemini did not return a response.',
                );

            }


            const result =
                JSON.parse(content);


            // ==========================================
            // STEP 7: IDENTIFY CAREER
            // ==========================================

            const detectedCareer =
                String(
                    result.career || '',
                ).trim();


            if (!detectedCareer) {

                throw new Error(
                    'Gemini did not identify a career.',
                );

            }


            // ==========================================
            // STEP 8: GET LATEST MARKET DEMAND
            // ==========================================

            const marketDemand =
                await this.marketDemandModel
                    .findOne({ userId })
                    .sort({
                        generatedAt: -1,
                        createdAt: -1,
                    });


            // ==========================================
            // STEP 9: FIND MATCHING MARKET CAREER
            // ==========================================

            const normalizeCareerName = (
                name: string,
            ) =>
                name
                    ?.toLowerCase()
                    .replace(/[^a-z0-9]/g, '') || '';


            const careerAliases:
                Record<string, string> = {

                // ----------------------------------
                // Frontend
                // ----------------------------------

                frontenddeveloper:
                    'frontenddeveloper',

                frontendengineer:
                    'frontenddeveloper',

                reactdeveloper:
                    'frontenddeveloper',

                reactjsdeveloper:
                    'frontenddeveloper',

                uideveloper:
                    'frontenddeveloper',

                webdeveloper:
                    'frontenddeveloper',

                frontendwebdeveloper:
                    'frontenddeveloper',


                // ----------------------------------
                // Backend
                // ----------------------------------

                backenddeveloper:
                    'backenddeveloper',

                backendengineer:
                    'backenddeveloper',

                nodejsdeveloper:
                    'backenddeveloper',

                nodejsengineer:
                    'backenddeveloper',

                nestjsdeveloper:
                    'backenddeveloper',


                // ----------------------------------
                // Full Stack
                // ----------------------------------

                fullstackdeveloper:
                    'fullstackdeveloper',

                fullstackengineer:
                    'fullstackdeveloper',

                fullstackwebdeveloper:
                    'fullstackdeveloper',


                // ----------------------------------
                // Data
                // ----------------------------------

                dataanalyst:
                    'dataanalyst',

                businessanalyst:
                    'dataanalyst',


                // ----------------------------------
                // Machine Learning / AI
                // ----------------------------------

                machinelearningengineer:
                    'machinelearningengineer',

                mlengineer:
                    'machinelearningengineer',

                aimlengineer:
                    'machinelearningengineer',

                aiengineer:
                    'machinelearningengineer',


                // ----------------------------------
                // Cybersecurity
                // ----------------------------------

                cybersecurityanalyst:
                    'cybersecurityanalyst',

                securityanalyst:
                    'cybersecurityanalyst',

                cybersecurityengineer:
                    'cybersecurityengineer',


                // ----------------------------------
                // DevOps / Cloud
                // ----------------------------------

                devopsengineer:
                    'devopsengineer',

                devopsdeveloper:
                    'devopsengineer',

                cloudengineer:
                    'cloudengineer',

            };


            const getCanonicalCareer = (
                name: string,
            ) => {

                const normalized =
                    normalizeCareerName(name);

                return (
                    careerAliases[normalized] ||
                    normalized
                );

            };


            let marketCareer: any = null;


            if (
                marketDemand?.careers?.length
            ) {

                const canonicalDetectedCareer =
                    getCanonicalCareer(
                        detectedCareer,
                    );


                // --------------------------------------
                // FIRST: CANONICAL CAREER MATCH
                // --------------------------------------

                marketCareer =
                    marketDemand.careers.find(
                        (career: any) =>
                            getCanonicalCareer(
                                career.career,
                            ) ===
                            canonicalDetectedCareer,
                    );


                // --------------------------------------
                // SECOND: COMMON JOB TITLES
                // --------------------------------------

                if (!marketCareer) {

                    marketCareer =
                        marketDemand.careers.find(
                            (career: any) => {

                                if (
                                    !Array.isArray(
                                        career.commonJobTitles,
                                    )
                                ) {

                                    return false;

                                }


                                return career.commonJobTitles.some(
                                    (title: string) =>
                                        getCanonicalCareer(
                                            title,
                                        ) ===
                                        canonicalDetectedCareer,
                                );

                            },
                        );

                }

            }


            // ==========================================
            // STEP 10: GET SHARED MATCH SCORE
            // AND SHARED ROADMAP
            // ==========================================

            let matchScore = 0;

            let sharedRoadmap: any[] = [];

            let matchedMarketCareer =
                detectedCareer;


            if (marketCareer) {

                matchScore =
                    Math.min(
                        100,

                        Math.max(
                            0,

                            Number(
                                marketCareer
                                    .userSkillMatch
                                    ?.matchPercentage,
                            ) || 0,

                        ),
                    );


                sharedRoadmap =
                    Array.isArray(
                        marketCareer.roadmap,
                    )
                        ? marketCareer.roadmap
                        : [];


                matchedMarketCareer =
                    marketCareer.career;

            }


            // ==========================================
            // STEP 11: SAVE ANALYSIS
            // ==========================================

            const analysis =
                await this.jobAnalysisModel.create({

                    userId,

                    jobDescription:
                        profile.jobDescription,

                    career:
                        matchedMarketCareer,

                    matchScore,

                    matchedSkills:
                        result.matchedSkills || [],

                    strengths:
                        result.strengths || [],

                    explanations:
                        result.explanations || [],

                    missingSkills:
                        result.missingSkills || [],


                    // ----------------------------------
                    // Shared roadmap from Market Demand
                    // ----------------------------------

                    generalRoadmap:
                        sharedRoadmap,


                    // ----------------------------------
                    // Keep old roadmap field empty
                    // for backward compatibility
                    // ----------------------------------

                    roadmap: [],

                });


            // ==========================================
            // STEP 12: RETURN RESULT
            // ==========================================

            return {

                message:
                    'Job analysis completed successfully.',

                analysis,

                marketDemandMatch:
                    Boolean(marketCareer),

            };


        } catch (error) {

            console.error(
                'Gemini Job Analysis Error:',
                error,
            );


            throw new InternalServerErrorException(
                'Failed to analyze the Job Description.',
            );

        }

    }


    // ==========================================
    // GET LATEST JOB ANALYSIS
    // ==========================================

    async getLatestAnalysis(
        userId: string,
    ) {

        const analysis =
            await this.jobAnalysisModel
                .findOne({ userId })
                .sort({
                    createdAt: -1,
                });


        if (!analysis) {

            throw new NotFoundException(
                'No job description analysis found.',
            );

        }


        return {

            message:
                'Latest job analysis retrieved successfully.',

            analysis,

        };

    }

}